/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kernel_NativeProcess */

#ifndef _Included_com_kernel_NativeProcess
#define _Included_com_kernel_NativeProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kernel_NativeProcess
 * Method:    CreateProcessA
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZJJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_kernel_NativeProcess_CreateProcessA
  (JNIEnv *, jclass, jstring, jstring, jboolean, jlong, jlong, jstring);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    ExitProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_kernel_NativeProcess_ExitProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    GetCommandLineA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kernel_NativeProcess_GetCommandLineA
  (JNIEnv *, jclass);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    GetCurrentProcess
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_kernel_NativeProcess_GetCurrentProcess
  (JNIEnv *, jclass);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    GetCurrentProcessorNumber
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_kernel_NativeProcess_GetCurrentProcessorNumber
  (JNIEnv *, jclass);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    GetEnvironmentVariable
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kernel_NativeProcess_GetEnvironmentVariable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    GetProcessTimes
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kernel_NativeProcess_GetProcessTimes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    OpenProcess
 * Signature: (JZJ)J
 */
JNIEXPORT jlong JNICALL Java_com_kernel_NativeProcess_OpenProcess
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_kernel_NativeProcess
 * Method:    TerminateProcess
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kernel_NativeProcess_TerminateProcess
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
